[package]
name = "outro_08"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
thiserror = "2.0.17"

[dependencies.rocket]
version = "0.5.1"
features = ["json"]
